### ISSUE TITLE
Unable to get edges with `SpecificVertexQuery.inbound`

### ISSUE THREAD

**Issue by C0MM4ND** [indradb/indradb#280]
I wrote a mini program for reproduction:

```rust
        // Create an in-memory datastore
        let db: indradb::Database<indradb::RocksdbDatastore> = indradb::RocksdbDatastore::new_db("tmpdb").unwrap();

        // Create a couple of vertices
        let out_v = indradb::Vertex::new(indradb::Identifier::new("person").unwrap());
        let in_v = indradb::Vertex::new(indradb::Identifier::new("movie").unwrap());
        db.create_vertex(&out_v).unwrap();
        db.create_vertex(&in_v).unwrap();

        // Add an edge between the vertices
        let edge = indradb::Edge::new(out_v.id, indradb::Identifier::new("likes").unwrap(), in_v.id);
        db.create_edge(&edge).unwrap();

        // Query for the edge, by outbound of the out_v
        let output = db.get(indradb::SpecificVertexQuery::new(vec![out_v.id]).outbound().unwrap()).unwrap();
        // Convenience function to extract out the edges from the query results
        let e = indradb::util::extract_edges(output).unwrap();
        println!("{:?}", e);
        assert_eq!(e.len(), 1);
        assert_eq!(edge, e[0]);
        // all works fine

        // Query for the edge, by inbound of the in_v
        let output_failed = db.get(indradb::SpecificVertexQuery::new(vec![in_v.id]).inbound().unwrap()).unwrap();
        // Convenience function to extract out the edges from the query results
        let e_failed = indradb::util::extract_edges(output_failed).unwrap();
        println!("{:?}", e_failed);
        assert_eq!(e_failed.len(), 1); // panic here
        assert_eq!(edge, e_failed[0]);
```

Error:
```
running 1 test
[Edge { outbound_id: 6375f969-ad62-11ed-8000-000000000000, t: Identifier(0x7f36ac0177a0 : "likes"), inbound_id: 6375f987-ad62-11ed-8001-000000000000 }]
[]
thread 'tests::test_inbound' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', src/main.rs:126:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:199:5
   4: test_indradb::tests::test_inbound
             at ./src/main.rs:126:9
   5: test_indradb::tests::test_inbound::{{closure}}
             at ./src/main.rs:99:23
   6: core::ops::function::FnOnce::call_once
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test tests::test_inbound ... FAILED
```

Apparently, the `inbound()` of `in_v` should have contained the `edge`, as what `outbound()` of `out_v` returns.

**Comment by C0MM4ND** [comment]
This bug wont appear when using `indradb::MemoryDatastore`
